### ISSUE TITLE
Can't properly create fields filter from Explorer

### ISSUE THREAD

**Issue by chinookproject** [strongloop/loopback-explorer#101]
The [Docs](http://docs.strongloop.com/display/public/LB/Fields+filter;jsessionid=38E493C55C78BBB41A29BAD756A12112) say that if you want to include or exclude a field from a resource then one have to create a filter like this:

```
api/pages?filter[fields][title]=false
```

However, there is no way to create this filter from the UI, because it always appends an equeal sign after `filter`. Resulting in this query string:

```
api/pages?filter=[fields][title]=false
```

**Comment by bajtos** [comment]
In the explorer, you have to encode the filter value as a json.

```json
{ "fields": { "title": false } }
```
