### ISSUE TITLE
Compare Swagger UI 1.0 and 2.0

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-explorer#112]
We are planning on upgrading to the latest version of the swagger-ui. Since we added several UI enhancements, we need to do a comparison of our swagger-ui 1.x fork and the current swagger-ui 2.x.

The two major UI additions I am aware of are:

 - visualizing response models
 - visualizing validation / json schema restrictions

Even if these are not implemented in in the swagger-ui 2.0, we are still going to upgrade to this version. This will provide a clear path to supporting swagger 2.0 spec in the explorer.

At this point we will evaluate how to re-implment our enhancements. We should try to upstream them, but might end up with another fork in order to add them in.

/cc @raymondfeng @ijroth @altsang @bajtos

**Comment by chandadharap** [comment]
Dup of strongloop-internal/scrum-loopback#412

**Comment by chandadharap** [comment]
closing.
