### ISSUE TITLE
Hide port number

### ISSUE THREAD

**Issue by safounder** [strongloop/loopback-explorer#121]
Hi there,

Just want to know is there way that i can hide the port number? 
i got a domain  www.web.com will normally host static content.
and i want to use api.web.com as loopback server. 
But at this moment, i only can use api.web.com:3000, can't use 80 because 80 is already in use.

Thanks.

**Comment by superkhau** [comment]
Unfortunately, this issue has nothing to do with LoopBack itself. You will probably need to do more research into setting up a web server to proxy requests from port 80 to `localhost:3000`. It's also different depending on the OS you're using. I suggest looking up how to do this on Google (you can try it without LoopBack to make sure it works).

**Comment by safounder** [comment]
Great, thanks.
