### ISSUE TITLE
loopback-explorer is no longer exposes as express router

### ISSUE THREAD

**Issue by kesavkolla** [strongloop/loopback-explorer#122]
The loopback standard example expects loopbac-explorer as express middle ware.

The explorer.js has the following code:
`
var explorer = require('loopback-explorer');
var explorerApp = explorer(server, {
        basePath: restApiRoot
    });
server.use('/explorer', explorerApp);
`
This is failing with error saying explorerApp is undefined.

**Comment by superkhau** [comment]
Did you try using the latest Loopback (ie. `npm install -g strongloop)? Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by superkhau** [comment]
I just scaffolded a new project, I don't see the error. Can also you provide the steps to reproduce?

**Comment by kesavkolla** [comment]
Here is the code in my server/boot/explorer.js

```
module.exports = function mountLoopBackExplorer(server) {
    'use strict';
    var explorer;
    try {
        explorer = require('loopback-explorer');
    } catch (err) {
        // Print the message only when the app was started via `server.listen()`.
        // Do not print any message when the project is used as a component.
        server.once('started', function (baseUrl) {
            console.log(
                'Run `npm install loopback-explorer` to enable the LoopBack explorer'
            );
        });
        return;
    }

    var restApiRoot = server.get('restApiRoot');

    var explorerApp = explorer(server, {
        basePath: restApiRoot
    });
    server.use('/explorer', explorerApp);
    server.once('started', function () {
        var baseUrl = server.get('url').replace(/\/$/, '');
        // express 4.x (loopback 2.x) uses `mountpath`
        // express 3.x (loopback 1.x) uses `route`
        var explorerPath = explorerApp.mountpath || explorerApp.route;
        console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    });
};
```

**Comment by superkhau** [comment]
I don't see `use strict` in the default explorer scaffolded by LB. Did you add this? Try scaffolding a new project via `slc loopback` locally and tell me if you still see the error.

**Comment by kesavkolla** [comment]
The standard `slc loopback` is using the loopback-explorer 1.x version.  I'm using loopback-explorer 2.x version that is where it's failing.

I just updated the regular scaffold and changed `package.json` with `"loopback-explorer": "*"`.  This is when it fails.

**Comment by raymondfeng** [comment]
2.x uses a different api. See https://github.com/strongloop/loopback-explorer#upgrading-from-v1x.
