### ISSUE TITLE
Client-side Uncaught TypeError with accept type: 'array' arguments

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-explorer#40]
Consider:

```
reorder.accepts = {
  arg: 'ids', type: 'array', required: true,
  http: { source: 'body' }
};
```
Uncaught TypeError: Cannot read property '$ref' of undefined at swagger.js line 710

**Comment by bajtos** [comment]
The type string `array` is not a valid value, you should use `['object']` instead. See http://docs.strongloop.com/display/LB/LoopBack+types#LoopBacktypes-Arraytypes

**Comment by bajtos** [comment]
I created a new issue to discuss `type: 'array'` support - see https://github.com/strongloop/loopback/issues/1327

**Comment by bajtos** [comment]
Fixed by https://github.com/strongloop/strong-remoting/pull/210, please upgrade your app to use `strong-remoting@2.17.0`.
