### ISSUE TITLE
Google Font timeout in local area network

### ISSUE THREAD

**Issue by gengen1988** [strongloop/loopback-explorer#74]
It cause me waiting 30 seconds until it timeout. I don't think a stylish typography is useful for developers.

**Comment by gengen1988** [comment]
Swigger UI now have font cache itself. Need pull request?

```html
<!DOCTYPE html>
<html>
<head>
  <title>Swagger UI</title>
  <link href='css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
```

**Comment by bajtos** [comment]
> Swigger UI now have font cache itself.

That is true for the upcoming 2.1 version. However, we are still at 2.0, which includes the external font in index.html. See yourself: https://github.com/swagger-api/swagger-ui/blob/v2.0.24/dist/index.html

The good news is that loopback-explorer overrides the CSS style and replaces the font-family "Droid Sans" with "Ubuntu", thus there is no reason to load the Droid Sans font in index.html.

> Need pull request?

Not needed, see https://github.com/strongloop/loopback-explorer/pull/87

**Comment by gengen1988** [comment]
Ubuntu, Native font? Tested on Windows and just seeing Arial. But it is OK. Finally no 30s timeout, lol
