### ISSUE TITLE
length of undefined error on timeout

### ISSUE THREAD

**Issue by HansHammel** [strongloop/loopback-explorer#76]
I came across the case where my server wasn't responding to put requests and noticed the api-explorer has no or a huge timeout on api calls. I was wondering it took so long, didn't expect it had no timeout. Well, the actual bug I wanted to report is:	

	PUT http://blabla:3000/api/pages/273541696466681878 net::ERR_EMPTY_RESPONSE shred.bundle.js:2608
	Uncaught TypeError: Cannot read property 'length' of undefined swagger-ui.js:2018
		OperationView.showStatus swagger-ui.js:2018
		OperationView.showErrorStatus swagger-ui.js:1899
		obj.on.error swagger.js:1159res.error swagger.js:1467
		EventEmitter.emit shred.bundle.js:1408
		emit shred.bundle.js:1189
		(anonymous function) shred.bundle.js:1208
		setBodyAndFinish shred.bundle.js:1815
		(anonymous function) shred.bundle.js:1832
		EventEmitter.emit shred.bundle.js:1388
		Response.handle shred.bundle.js:2715
		xhr.onreadystatechange shred.bundle.js:2584

**Comment by fehguy** [comment]
I cannot seem to reproduce this.  If you can help provide a test case or server configuration that causes it, please feel free to add details:  https://github.com/swagger-api/swagger-js/issues/187

**Comment by bajtos** [comment]
I am closing the issue then. @HansHammel feel free to reopen if you can provide details on how to reproduce the problem.
