### ISSUE TITLE
`uiDirs` should take a String or Array

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-explorer#81]
As per discussions with @dashby3000 and @chandadharap, we should allow a String value for a single static dir or an Array of paths for multiple static dirs.

> See https://github.com/strongloop/loopback-explorer/blob/master/index.js#L54

**Comment by ritch** [comment]
Next time just assign the PR to me then it will show up in my review queue. Keep the issue assigned to yourself.

**Comment by superkhau** [comment]
Sounds good.
