### ISSUE TITLE
Upgrade the Swagger UI

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-explorer#92]
It would be nice to get a newer swagger UI in the explorer. The one we have now is incredibly old.

**Edit: ok its not that old... but still.**

I'm guessing the following people will be interested in this (please chime in if you have specifics):

@bajtos @raymondfeng @shelbys @STRML

**Comment by bajtos** [comment]
> The one we have now is incredibly old.

Not that old, 2.0.24 was released on Sep 13, 2014. The 2.1 version is still not done, the latest release is 2.1.0-M2.

**Comment by dashby3000** [comment]
Yes, this will have a big effect on the GoDaddy implementation.  We should talk about the changes.

**Comment by shelbys** [comment]
@ritch - FYI, our fork is already on 2.1.3, so it may be best to just backstitch our changes, see: https://github.com/shelbys/swagger-ui/blob/master/package.json

**Comment by shelbys** [comment]
@ritch - My mistake, ours is based on `2.0.23`.  The other version bumps have been for local additions
