### ISSUE TITLE
Filters not creating valid queries

### ISSUE THREAD

**Issue by mattwoolnough** [strongloop/loopback-explorer#94]
entering a simple filter in explorer 1.7.2.

[order]=ts DESC

explorer populates query as:
http://localhost:3000/api/Entry?filter=[order]=ts DESC&filter[limit]=1
instead of:
http://localhost:3000/api/Entry?filter[order]=ts DESC&filter[limit]=1

resulting in 400 error.

Also, on a more minor note explorer lists 
Filter defining fields, where, orderBy, offset, and limit
instead of 
Filter defining fields, where, order, offset, and limit

**Comment by raymondfeng** [comment]
In the explorer, you need to provide the filter value as stringified json.

**Comment by mattwoolnough** [comment]
It works perfectly using the square brackets style too if you remove the unnecessary equals symbol.

**Comment by bajtos** [comment]
I am afraid this is a limitation of Swagger UI that we are not going to fix.

You should compose the filter argument as JSON:

```
{ "order": "ts DESC", "limit": 1 }
```

**Comment by cfjedimaster** [comment]
I just ran into this myself - even if you can't fix it - is there anyway you can simply add some text to the UI to explain how to pass the value?

**Comment by bajtos** [comment]
>  is there anyway you can simply add some text to the UI to explain how to pass the value?

I believe the UI shows the contents of `description` from argument's remoting metadata. Perhaps we can modify this field to include the additional help? See e.g.
https://github.com/strongloop/loopback/blob/c69e010670a4289d65e188968c54042bbf04bc28/lib/persisted-model.js#L752-L753

@cfjedimaster would you like to contribute this change yourself?

**Comment by cfjedimaster** [comment]
@bajtos id be happy to - but i noticed the code you linked too had this:

Filter defining fields and include

In a new LB 3 app, in explorer, I see this:

Filter defining fields, where, include, order, offset, and limit

Any idea why?

**Comment by cfjedimaster** [comment]
Ah - theres 3 descriptions like this, and one matches the one you linked to. I get it now. Working on a PR.

**Comment by cfjedimaster** [comment]
PR filed

**Comment by bajtos** [comment]
Thank you, I have landed your improvement to both `2.x` and `master` branches of LoopBack.
